import { Opportunity, User } from '@/types';

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-001',
    rank: 1,
    title: 'Agentic AI Workflow Automation',
    summary: 'Multi-step autonomous AI agents replacing repetitive knowledge work across enterprise back-offices.',
    fullSummary: 'Agentic AI systems have crossed the threshold from demo to deployment in 2024–2025. Unlike simple LLM chatbots, these multi-agent pipelines can reason, plan, use tools, and complete complex workflows across enterprise systems without human intervention. The shift is from AI as assistant to AI as autonomous operator — completing tasks end-to-end across CRM, ERP, logistics, and finance platforms. Enterprises in SEA are beginning pilots, particularly in Singapore and Thailand.',
    category: 'Emerging Tech',
    hypeType: 'Traction',
    hypeExplanation: 'GitHub repos for agent frameworks (LangGraph, CrewAI, AutoGen) show 300%+ growth in stars. Enterprise deals with Salesforce, SAP, and ServiceNow integrations are being announced monthly. Revenue traction is measurable.',
    seaStatus: 'No SEA Competitor',
    seaAnalysis: 'No locally headquartered pure-play agentic AI vendor operates at scale in SEA as of Q1 2025. Most deployments are extensions of US/EU SaaS platforms. First-mover window remains open for a SEA-native orchestration layer.',
    amastAligned: true,
    amastPillars: ['AI', 'Sales & Distribution'],
    amastDetails: "Direct fit with AMAST AI capability. Agentic orchestration can automate field sales reporting, distributor reconciliation, and back-office ops for AMAST's merchandising and distribution clients.",
    score: 92,
    scoreBreakdown: { marketSize: 18, innovation: 17, seaFit: 16, timing: 16, competition: 15, amastFit: 10, total: 92 },
    dateDiscovered: '2025-01-15',
    curationStatus: 'Interested',
    businessModel: 'SaaS subscription per seat + usage-based token consumption. Target: enterprise SMBs at $500–$2,000/month. Adjacent revenue: implementation services, custom agent development.',
    velocityData: [
      { month: 'Aug 24', score: 54, isRecent: false },
      { month: 'Sep 24', score: 61, isRecent: false },
      { month: 'Oct 24', score: 69, isRecent: false },
      { month: 'Nov 24', score: 78, isRecent: false },
      { month: 'Dec 24', score: 85, isRecent: true },
      { month: 'Jan 25', score: 92, isRecent: true },
    ],
    trendHistory: [
      { date: '2024-11-20', rank: 4, score: 78, hypeType: 'Hype' },
      { date: '2024-12-10', rank: 2, score: 85, hypeType: 'Hype' },
      { date: '2025-01-05', rank: 1, score: 90, hypeType: 'Traction' },
      { date: '2025-01-15', rank: 1, score: 92, hypeType: 'Traction' },
    ],
    notes: '',
  },
  {
    id: 'opp-002',
    rank: 2,
    title: 'Cold Chain Visibility Platform',
    summary: 'IoT + AI platform providing real-time end-to-end temperature and condition monitoring for pharmaceutical and FMCG logistics.',
    fullSummary: 'Cold chain failures cost the global economy $35B annually in spoilage. Modern cold chain visibility platforms combine BLE/RFID sensors, cellular IoT gateways, and AI-driven anomaly detection to provide continuous end-to-end monitoring. SEA is a high-growth market due to the explosion of pharmaceutical distribution, modern trade expansion, and government mandates for cold chain compliance in Indonesia, Malaysia, and the Philippines.',
    category: 'Emerging SaaS',
    hypeType: 'Traction',
    hypeExplanation: 'Multiple Series B rounds closed in 2024 (Parsyl, Controlant). Customer count growth of 180% YoY in SEA. Driven by regulatory pressure and pharma supply chain modernization.',
    seaStatus: 'Competitor Exists',
    seaAnalysis: 'Competitors include Cogoport (India-originated), and SaaS extensions from DHL and DB Schenker. However, no pure-play SEA-native vendor with pharmaceutical-grade compliance has scaled across more than two markets.',
    amastAligned: true,
    amastPillars: ['Logistics', 'RFID'],
    amastDetails: 'Strong convergence with AMAST Logistics and RFID pillars. AMAST already has sensor integration expertise; adding cold chain monitoring as a vertical expansion is achievable within 6–12 months.',
    score: 87,
    scoreBreakdown: { marketSize: 17, innovation: 14, seaFit: 18, timing: 15, competition: 13, amastFit: 10, total: 87 },
    dateDiscovered: '2025-01-15',
    curationStatus: 'Follow Up',
    businessModel: 'Hardware-as-a-Service (sensor leasing) + SaaS dashboard at $8–$15 per sensor/month. Enterprise contracts $50K–$500K ACV. Upsell: compliance reporting, insurance integration.',
    velocityData: [
      { month: 'Aug 24', score: 60, isRecent: false },
      { month: 'Sep 24', score: 65, isRecent: false },
      { month: 'Oct 24', score: 72, isRecent: false },
      { month: 'Nov 24', score: 78, isRecent: false },
      { month: 'Dec 24', score: 83, isRecent: true },
      { month: 'Jan 25', score: 87, isRecent: true },
    ],
    trendHistory: [
      { date: '2024-10-30', rank: 5, score: 70, hypeType: 'Traction' },
      { date: '2024-12-10', rank: 3, score: 80, hypeType: 'Traction' },
      { date: '2025-01-15', rank: 2, score: 87, hypeType: 'Traction' },
    ],
    notes: 'Spoke to 3 logistics contacts — all flagged cold chain compliance as a top pain point in Malaysia. Worth a demo.',
  },
  {
    id: 'opp-003',
    rank: 3,
    title: 'AI-Powered Retail Planogram Optimization',
    summary: 'Computer vision + GenAI platform that automatically audits shelf compliance and recommends optimal product placement.',
    fullSummary: 'Traditional planogram audits require field visits and manual photography review — an expensive, slow, and error-prone process. New platforms use smartphone cameras or fixed store cameras with computer vision models to detect out-of-stock, misplacement, or planogram deviations in real-time. GenAI layers then recommend corrective actions and optimal shelf layouts. For CPG brands and modern trade retailers in SEA, this represents a massive efficiency gain.',
    category: 'Emerging Tech',
    hypeType: 'Hype',
    hypeExplanation: 'Significant investor interest and press coverage, but enterprise deployments remain in early pilot phase. Most solutions require expensive hardware infrastructure. Mass adoption is 18–24 months away.',
    seaStatus: 'No SEA Competitor',
    seaAnalysis: 'Trax Retail (Singapore-based) is the closest competitor but focuses primarily on image capture rather than AI-driven optimization. No local vendor has combined CV + GenAI planogram recommendation at scale in SEA.',
    amastAligned: true,
    amastPillars: ['AI', 'Sales & Distribution'],
    amastDetails: 'Perfect alignment with AMAST merchandising operations. AMAST already conducts planogram audits for retail clients — this technology can be integrated into existing field visit workflows.',
    score: 81,
    scoreBreakdown: { marketSize: 15, innovation: 17, seaFit: 14, timing: 13, competition: 14, amastFit: 8, total: 81 },
    dateDiscovered: '2025-01-08',
    curationStatus: 'Interested',
    businessModel: 'Per-store subscription at $200–$800/month. Revenue share with CPG brands based on measured sales uplift. Implementation fee: $15K–$50K per retailer.',
    velocityData: [
      { month: 'Aug 24', score: 45, isRecent: false },
      { month: 'Sep 24', score: 52, isRecent: false },
      { month: 'Oct 24', score: 60, isRecent: false },
      { month: 'Nov 24', score: 68, isRecent: false },
      { month: 'Dec 24', score: 75, isRecent: true },
      { month: 'Jan 25', score: 81, isRecent: true },
    ],
    trendHistory: [
      { date: '2024-11-05', rank: 7, score: 64, hypeType: 'Hype' },
      { date: '2024-12-20', rank: 4, score: 74, hypeType: 'Hype' },
      { date: '2025-01-08', rank: 3, score: 81, hypeType: 'Hype' },
    ],
    notes: '',
  },
  {
    id: 'opp-004',
    rank: 4,
    title: 'Embedded Finance for Distributor Networks',
    summary: 'Buy-now-pay-later and working capital financing embedded directly into distributor management software.',
    fullSummary: 'Embedded finance is moving downstream from consumer to B2B. Distributor networks in SEA — particularly in FMCG, pharmaceuticals, and building materials — face chronic working capital constraints. Embedding BNPL and invoice financing directly into DMS platforms removes friction and unlocks trade volumes. Several fintech platforms have pivoted to B2B embedded finance, targeting the $1.2T annual trade finance gap in SEA.',
    category: 'Emerging SaaS',
    hypeType: 'Traction',
    hypeExplanation: 'Funding activity is strong: Lending in a Box (Malaysia), Anchanto-adjacent plays, and regional banks building embedded APIs. Customer adoption is measurable with default rates under control.',
    seaStatus: 'Competitor Exists',
    seaAnalysis: 'PayWatch, Funding Societies, and Validus are active in this space. However, none have deeply embedded financing within a sector-specific DMS — they remain standalone fintech products.',
    amastAligned: true,
    amastPillars: ['Sales & Distribution', 'Logistics'],
    amastDetails: 'AMAST operates a distributor management platform. Embedding working capital financing would increase platform stickiness and unlock a revenue-share model with fintech partners.',
    score: 76,
    scoreBreakdown: { marketSize: 16, innovation: 12, seaFit: 16, timing: 14, competition: 10, amastFit: 8, total: 76 },
    dateDiscovered: '2024-12-20',
    curationStatus: 'Follow Up',
    businessModel: 'Revenue share on origination (1.5–3% of financed amount). SaaS fee for DMS integration API. Potential equity stake in embedded fintech JV.',
    velocityData: [
      { month: 'Aug 24', score: 55, isRecent: false },
      { month: 'Sep 24', score: 59, isRecent: false },
      { month: 'Oct 24', score: 63, isRecent: false },
      { month: 'Nov 24', score: 67, isRecent: false },
      { month: 'Dec 24', score: 72, isRecent: true },
      { month: 'Jan 25', score: 76, isRecent: true },
    ],
    trendHistory: [
      { date: '2024-10-15', rank: 8, score: 62, hypeType: 'Hype' },
      { date: '2024-11-20', rank: 6, score: 68, hypeType: 'Traction' },
      { date: '2024-12-20', rank: 4, score: 76, hypeType: 'Traction' },
    ],
    notes: '',
  },
  {
    id: 'opp-005',
    rank: 5,
    title: 'Decentralised RFID Track-and-Trace for Pharmaceuticals',
    summary: 'Blockchain-anchored RFID serialisation platform for pharmaceutical supply chain integrity and anti-counterfeiting.',
    fullSummary: 'Pharmaceutical counterfeiting costs SEA governments and healthcare systems billions annually. RFID serialisation combined with blockchain immutability creates an auditable chain-of-custody from manufacturer to patient. New platforms use low-cost passive RFID tags with blockchain anchoring to enable real-time authentication at any point in the supply chain. Malaysia and Indonesia have both introduced draft regulations requiring serialisation for high-risk drug categories.',
    category: 'Emerging Tech',
    hypeType: 'Hype',
    hypeExplanation: 'Regulatory tailwinds are strong but compliance deadlines keep slipping. Technology is proven in pilots but mass commercial deployment is held back by cost per unit and standardisation issues.',
    seaStatus: 'No SEA Competitor',
    seaAnalysis: 'MediLedger (US) and Movilitas (Germany) serve global pharma but have minimal SEA presence. No locally integrated serialisation platform has achieved regulatory certification in more than one SEA market.',
    amastAligned: true,
    amastPillars: ['RFID', 'Logistics'],
    amastDetails: 'Core AMAST capability. AMAST already deploys RFID in retail and logistics; pharmaceutical serialisation is a direct vertical extension with high compliance-driven switching costs.',
    score: 73,
    scoreBreakdown: { marketSize: 14, innovation: 15, seaFit: 14, timing: 12, competition: 12, amastFit: 6, total: 73 },
    dateDiscovered: '2024-12-20',
    curationStatus: 'Interested',
    businessModel: 'Per-unit RFID tag pricing + SaaS compliance dashboard. Regulatory reporting module as upsell. Government tender opportunities for national serialisation infrastructure.',
    velocityData: [
      { month: 'Aug 24', score: 50, isRecent: false },
      { month: 'Sep 24', score: 53, isRecent: false },
      { month: 'Oct 24', score: 58, isRecent: false },
      { month: 'Nov 24', score: 63, isRecent: false },
      { month: 'Dec 24', score: 68, isRecent: true },
      { month: 'Jan 25', score: 73, isRecent: true },
    ],
    trendHistory: [
      { date: '2024-09-10', rank: 10, score: 55, hypeType: 'Hype' },
      { date: '2024-11-20', rank: 7, score: 63, hypeType: 'Hype' },
      { date: '2024-12-20', rank: 5, score: 73, hypeType: 'Hype' },
    ],
    notes: '',
  },
  {
    id: 'opp-006',
    rank: 6,
    title: 'AI Video Intelligence for Retail Footfall',
    summary: 'Privacy-preserving computer vision platform analysing in-store customer behaviour, heatmaps, and conversion funnels.',
    fullSummary: 'Brick-and-mortar retail in SEA is fighting back against e-commerce by using AI-powered video analytics to understand customer behaviour at a granular level. Privacy-preserving platforms (using silhouette detection rather than facial recognition) produce heatmaps, dwell time analysis, and conversion funnel insights without PII concerns. The technology is mature in Europe but remains largely underpenetrated in SEA modern trade.',
    category: 'Emerging Tech',
    hypeType: 'Traction',
    hypeExplanation: 'Quividi, Ipsos Retail, and Deepnorth report strong renewal rates. SEA deployments growing 90% YoY from a small base. Real revenue with measurable ROI for retailers.',
    seaStatus: 'Competitor Exists',
    seaAnalysis: 'Quividi and VSBLTY have SEA distribution partnerships. However, both rely on hardware resellers with limited local support — creating an opening for a managed service offering.',
    amastAligned: false,
    amastPillars: [],
    amastDetails: '',
    score: 68,
    scoreBreakdown: { marketSize: 14, innovation: 13, seaFit: 13, timing: 11, competition: 10, amastFit: 7, total: 68 },
    dateDiscovered: '2025-01-08',
    curationStatus: 'Unreviewed',
    businessModel: 'Camera-as-a-Service subscription $150–$400/camera/month. Analytics dashboard SaaS fee. Professional services for custom dashboard and API integrations.',
    velocityData: [
      { month: 'Aug 24', score: 44, isRecent: false },
      { month: 'Sep 24', score: 49, isRecent: false },
      { month: 'Oct 24', score: 54, isRecent: false },
      { month: 'Nov 24', score: 59, isRecent: false },
      { month: 'Dec 24', score: 64, isRecent: true },
      { month: 'Jan 25', score: 68, isRecent: true },
    ],
    trendHistory: [
      { date: '2024-11-05', rank: 9, score: 58, hypeType: 'Traction' },
      { date: '2024-12-20', rank: 7, score: 64, hypeType: 'Traction' },
      { date: '2025-01-08', rank: 6, score: 68, hypeType: 'Traction' },
    ],
    notes: '',
  },
  {
    id: 'opp-007',
    rank: 7,
    title: 'Micro-Fulfilment Centre Software',
    summary: 'SaaS platform for managing hyper-local dark stores and micro-warehouses serving 2-hour urban delivery.',
    fullSummary: 'Q-commerce (quick commerce) has normalised 2-hour delivery expectations in SEA urban centres. Retailers and 3PLs are retrofitting petrol stations, carparks, and retail backrooms into micro-fulfilment centres (MFCs). Managing inventory, picking, and last-mile dispatch across dozens of MFCs requires purpose-built WMS software that is fundamentally different from traditional warehouse management systems. The market is growing explosively but software is lagging behind hardware investment.',
    category: 'Emerging SaaS',
    hypeType: 'Hype',
    hypeExplanation: 'Strong VC interest in q-commerce infrastructure but operator unit economics remain challenged. Several operators have scaled back. Software demand is real but growth assumptions are being recalibrated.',
    seaStatus: 'No SEA Competitor',
    seaAnalysis: 'Takeoff Technologies (US) and Attabotics (Canada) serve global enterprise. No SEA-native MFC software vendor has more than 3 live deployments. Large opportunity for a region-specific platform.',
    amastAligned: true,
    amastPillars: ['Logistics'],
    amastDetails: 'AMAST Logistics capability could extend into MFC orchestration software, particularly for FMCG brand clients looking to run distributed micro-warehousing.',
    score: 62,
    scoreBreakdown: { marketSize: 13, innovation: 12, seaFit: 11, timing: 10, competition: 11, amastFit: 5, total: 62 },
    dateDiscovered: '2024-11-20',
    curationStatus: 'Rejected',
    businessModel: 'SaaS per MFC location at $1,500–$5,000/month. Pick-and-pack API fee per order. Integration services for grocery POS and last-mile delivery platforms.',
    velocityData: [
      { month: 'Aug 24', score: 70, isRecent: false },
      { month: 'Sep 24', score: 72, isRecent: false },
      { month: 'Oct 24', score: 68, isRecent: false },
      { month: 'Nov 24', score: 65, isRecent: false },
      { month: 'Dec 24', score: 63, isRecent: true },
      { month: 'Jan 25', score: 62, isRecent: true },
    ],
    trendHistory: [
      { date: '2024-09-10', rank: 3, score: 72, hypeType: 'Hype' },
      { date: '2024-10-30', rank: 5, score: 68, hypeType: 'Hype' },
      { date: '2024-11-20', rank: 7, score: 62, hypeType: 'Hype' },
    ],
    notes: 'Rejected — q-commerce operator landscape too volatile. Revisit in 12 months.',
  },
  {
    id: 'opp-008',
    rank: 8,
    title: 'Sales Rep Performance Intelligence',
    summary: 'AI-powered coaching platform that analyses field sales rep behaviour and provides personalised performance recommendations.',
    fullSummary: 'Traditional sales management relies on lagging indicators: call reports, revenue attainment, and manager observation. AI performance intelligence platforms instrument the sales process — call transcripts, CRM activity, route adherence, outlet visit quality — and surface leading indicators of underperformance before deals are lost. In SEA markets where field sales forces are large and turnover is high, early warning systems deliver measurable ROI.',
    category: 'Emerging SaaS',
    hypeType: 'Traction',
    hypeExplanation: 'Gong, Clari, and Mindtickle report strong NRR and expansion revenue. SEA-specific platforms gaining traction with CPG and pharma sales forces. Measurable ROI (10–20% revenue uplift) drives contract renewals.',
    seaStatus: 'No SEA Competitor',
    seaAnalysis: 'Gong and Clari are US-centric and do not integrate with SEA CRM and DMS ecosystems. Local sales analytics vendors (e.g., StoreHub add-ons) lack the AI coaching layer. Clear market gap.',
    amastAligned: true,
    amastPillars: ['AI', 'Sales & Distribution'],
    amastDetails: "AMAST manages large field sales forces for CPG clients. A rep performance intelligence layer bolted onto AMAST's existing Sales & Distribution platform would increase platform value and retention.",
    score: 58,
    scoreBreakdown: { marketSize: 12, innovation: 12, seaFit: 10, timing: 11, competition: 9, amastFit: 4, total: 58 },
    dateDiscovered: '2024-11-20',
    curationStatus: 'Unreviewed',
    businessModel: 'Per-seat SaaS $30–$80/rep/month. Enterprise deals at $100K–$500K ACV for large field forces. Training content marketplace as upsell.',
    velocityData: [
      { month: 'Aug 24', score: 38, isRecent: false },
      { month: 'Sep 24', score: 42, isRecent: false },
      { month: 'Oct 24', score: 47, isRecent: false },
      { month: 'Nov 24', score: 51, isRecent: false },
      { month: 'Dec 24', score: 55, isRecent: true },
      { month: 'Jan 25', score: 58, isRecent: true },
    ],
    trendHistory: [
      { date: '2024-09-10', rank: 12, score: 42, hypeType: 'Hype' },
      { date: '2024-10-30', rank: 10, score: 49, hypeType: 'Hype' },
      { date: '2024-11-20', rank: 8, score: 58, hypeType: 'Traction' },
    ],
    notes: '',
  },
];

export const mockUsers: User[] = [
  { id: 'usr-001', name: 'Januah Musa', email: 'januah@amast.com.my', role: 'Admin', status: 'Active' },
  { id: 'usr-002', name: 'Rafiq Ismail', email: 'rafiq@amast.com.my', role: 'Analyst', status: 'Active' },
  { id: 'usr-003', name: 'Siti Norzahra', email: 'siti@amast.com.my', role: 'Analyst', status: 'Active' },
  { id: 'usr-004', name: 'James Tan', email: 'james.tan@amast.com.my', role: 'Viewer', status: 'Active' },
  { id: 'usr-005', name: 'Priya Krishnan', email: 'priya@amast.com.my', role: 'Viewer', status: 'Inactive' },
];

export const AVAILABLE_DATES = [
  '2025-01-15',
  '2025-01-08',
  '2024-12-20',
  '2024-11-20',
  '2024-10-30',
  '2024-09-10',
];
